### ISSUE TITLE
what does your Procfile look like?

### ISSUE THREAD

**Issue by cbanowsky** [current/vuash#81]

**Comment by jonduarte** [comment]
@cbanowsky I added it to the repo. It is pretty straightforward, just a default heroku `Procfile`.

**Comment by cbanowsky** [comment]
I can't deploy to heroku for the life of me.  Application error.  Any suggestions?  I have deployed, node and ruby apps, but this one is giving me trouble and it is one i really like :)

**Comment by rmasoni** [comment]
Hey, are you deploying from the `master` branch? Did you run the basic rake tasks for creating and migrating the database?

**Comment by cbanowsky** [comment]
Yes master branch.  I did my basic rake tasks and everything seemed fine.  It even deployed fine, but url showed application error.

**Comment by rmasoni** [comment]
Um… I can't remember doing anything extraordinary to have it up and running. What comes up in the logs?

**Comment by cbanowsky** [comment]
I ended up changing webserver and config vars got it going :)

**Comment by rmasoni** [comment]
Good to know! Have fun!
